version: '3.8'

volumes:
    postgres_db:
  
services:
  db:
    image: postgres:12.0
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  api:
    build: ./news_api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
